---
title: "Question"
author: "Husky"
date: "4/22/2019"
output: html_document
---

2012

1:  36. Which of the following tobacco products have you ever heard of?

2:    37. Which of the following tobacco products have you ever tried, even just one time?

3:    38.During the past 30 days, which of the following products have you used on at least one day?
    
4:   69. Do you believe that electronic cigarettes or e-cigarettes, such as Ruyan or NJOY, are (LESS HARMFUL, EQUALLY HARMFUL, orMOREHARMFUL)thanregular cigarettes?




2014

  The next six questions are about the use of electronic cigarettes or e-cigarettes such as blu, 21st Century Smoke or NJOY.

1:     30. Have you ever been curious about using an electronic cigarette or e-cigarette such as blu, 21st Century Smoke or NJOY?

2:      31. Have you ever tried an electronic cigarette or e-cigarette such as blu, 21st Century Smoke or NJOY?

3:      32. Do you think that you will try an electronic cigarette or e-cigarette soon?

4:      33. If one of your best friends were to offer you an electronic cigarette or e-cigarette, would you use it?

5:      34. How old were you when you first tried using an electronic cigarette or e-cigarette?

6       35. During the past 30 days, on how many days did you use electronic cigarettes or e-cigarettes such as blu, 21st Century Smoke, or NJOY?
      
      
7:      38. Which of the following tobacco products that you used in the past 30 days were flavored to taste like menthol (mint), alcohol (wine, cognac), candy, fruit, chocolate or other sweets 


8:      39. Which of the following tobacco products did you try first


9:      59. How much do you think people harm themselves when they use e-cigarettes some days but not every day?


10:     60. Do you believe that e-cigarettes are (LESS HARMFUL, EQUALLY HARMFUL, or MORE HARMFUL) than regular cigarettes?

11:     61. Do you believe that e-cigarettes are (LESS ADDICTIVE, EQUALLY ADDICTIVE, or MORE ADDICTIVE) than cigarettes?

12:     69. When you read newspapers or magazines, how often do you see ads or promotions for electronic cigarettes or e-cigarettes?

13:     70. When you go to a convenience store, supermarket, or gas station, how often do you see ads or promotions for electronic cigarettes or e-cigarettes?

14:     71. When you watch TV or go to the movies, how often do you see ads or promotions for electronic cigarettes or e-cigarettes?

15:     79. Do you think young people who use electronic cigarettes or e-cigarettes have more friends?

16:     80. Does anyone who lives with you now...? 



2015

The next twelve questions are about electronic cigarettes or e-cigarettes. E-cigarettes are electronic devices that usually contain a nicotine-based liquid that is vaporized and inhaled. You may also know them as vape-pens, hookah-pens, electronic hookahs (e-hookahs),electronic cigars (e-cigars), electronic pipes (e-pipes), or e- vaporizers. Some look like cigarettes and others look like pens or small pipes. These are battery-powered devices that produce vapor instead of smoke. Some brands examples are NJOY, Blu, VUSE, MarkTen, Finiti, Starbuzz, and Fantasia.

1: 27. Have you ever been curious about using an electronic cigarette or e-cigarette, even once or twice?

2: 28. Have you ever used an electronic cigarette or e-cigarette, even once or twice?

3: 29. Do you think that you will try an electronic cigarette or e-cigarette soon?

4:  30. If one of your best friends were to offer you an electronic cigarette or e-cigarette, would you use it?

5:  31. How old were you when you first tried using an electronic cigarette or e-cigarette, even once or twice?

6:  32. During the past 30 days, on how many days did you use electronic cigarettes or e-cigarettes?

7:  33. In total, on how many days have you used an electronic cigarette or e-cigarette in your entire life?

8:  34. What brands of electronic cigarettes or e-cigarettes have you ever tried?

9:  35. Thinking about all types of electronic cigarettes or e-cigarettes, have you used the disposable kind or rechargeable/refillable tank kind?

10: 36. Which of the following statements best applies to your cigarette or electronic cigarette use?

11: 37. What are the reasons why you have used electronic cigarettes or e-cigarettes?

12: 38. Have you ever used an electronic cigarette device for any other substance other than for nicotine?

13: 41. Which of the following tobacco products that you used in the past 30 days were flavored to taste like menthol (mint), alcohol (wine, cognac), candy, fruit, chocolate or other sweets? 

14: 42. Which of the following tobacco products did you try first?

15: 59. How much do you think people harm themselves when they use e-cigarettes some days but not every day?

16: 69. When you are using the Internet, how often do you see ads or promotions for electronic cigarettes or e-cigarettes?

17: 71. When you go to a convenience store, supermarket, or gas station, how often do you see ads or promotions for electronic cigarettes or e-cigarettes?

18: 72. When you watch TV, how often do you see ads or promotions for electronic cigarettes or e-cigarettes?



The next four questions ask about you being around other people’s tobacco smoke or vapor from electronic cigarettes or e-cigarettes.

19: 76. During the past 30 days, on how many days did you breathe the vapor from someone who was using an electronic cigarette or e-cigarette in an indoor or outdoor public place? Examples of indoor public places are school buildings, stores, restaurants, and sports arenas. Examples of outdoor public places are school grounds, parking lots, stadiums and parks.

20: 77. Does anyone who lives with you now...?

21: 45. During the past 30 days, where did you get or buy the electronic cigarettes that you have used? 




2017

The next 11 questions are about electronic cigarettes or e-cigarettes. E-cigarettes are battery powered devices that usually contain a nicotine-based liquid that is vaporized and inhaled. You may also know them as e-cigs, vape-pens, hookah-pens, e-hookahs, e-cigars, e-pipes, personal vaporizers, or mods. Some brand examples include NJOY, Blu, Vuse, MarkTen, Logic, Vapin Plus, eGo, and Halo.

1:  27. Have you ever been curious about using an e-cigarette?

2:  28. Have you ever used an e-cigarette, even once or twice?

3:  29. How old were you when you first tried using an e-cigarette, even once or twice?

4:  30. In total, on how many days have you used e-cigarettes in your entire life?

5:  31. During the past 30 days, on how many days did you use e-cigarettes?

6:  32. During the past 30 days, where did you get or buy the e-cigarettes that you have used?

7:  33. What are the reasons you have used e-cigarettes? 

8:  35. Do you think that you will try an e-cigarette soon?

9:  36. Do you think you will use an e-cigarette in the next year?

10: 37. If one of your best friends were to offer you an e-cigarette, would you use it?

11: 49. Which of the following tobacco products that you used in the past 30 days were flavored to taste like menthol (mint), alcohol (wine, cognac), candy, fruit, chocolate or any other flavors? 

12: 62. During the past 30 days, how often did you see a warning label on an e-cigarette package?

13: 68. How much do you think people harm themselves when they use e-cigarettes some days but not every day?

14: 69. Do you believe that e-cigarettes are (LESS ADDICTIVE, EQUALLY ADDICTIVE, or MORE ADDICTIVE) than cigarettes?

15: 78. When you are using the Internet, how often do you see ads or promotions for e-cigarettes?

16: 79. When you read newspapers or magazines, how often do you see ads or promotions for e-cigarettes?

17: 80. When you go to a convenience store, supermarket, or gas station, how often do you see ads or promotions for e-cigarettes?

18: 81. When you watch TV, how often do you see ads or promotions for e-cigarettes?


The next question asks about being around other people’s e-cigarette vapor. Do not include exposure to smoke from other tobacco products.
19: 85. During the past 30 days, on how many days did you breathe the vapor from someone who was using an e-cigarette in an indoor or outdoor public place? Examples of indoor public places are school buildings, stores, restaurants, and sports arenas. Examples of outdoor public places are school grounds, parking lots, stadiums, and parks.

20: 86. Does anyone who lives with you now...? 

21: 34. Have you ever used marijuana, marijuana concentrates, marijuana waxes, THC, or hash oils in an e- cigarette?

22: 









